language: python

script:
  - python -m pytest -v tests/test_generator.py

services:
  - docker
     
after_success:
          - sh .travis/deploy_dockerhub.sh

after_success:
  - sh .travis/deploy_dockerhub.sh
  - test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh
